name: Resharper Code Analysis
 
on: 
    push:
        branches: [main]
 
jobs:
  resharper:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install resharper
        run: dotnet tool install -g JetBrains.ReSharper.GlobalTools

      - name: Adding Main Project Packages
        run: dotnet add AssistPurchase/AssistPurchase.csproj package System.Data.SQLite.Core --version 1.0.113.1

      - name: Adding Test Project Packages
        run: dotnet add AssistPurchase.Test/AssistPurchase.Test.csproj package xunit --version 2.4.0
        
      - name: Run resharper inspection
        run: jb inspectcode AssistPurchase.sln /output=insreport.xml
       
      - name: Run resharper duplicate code check
        run: jb dupfinder AssistPurchase.sln /output=dupreport.xml
       
      - name: Check Reports
        run: powershell ./resharper.ps1